### ISSUE TITLE
[1.1.0] Uncaught (in promise) ReferenceError: gear is not defined

### ISSUE THREAD

**Issue by ArmandVestibule** [Brownie79/fvtt-swade-stat-block-parser#2]
When attempting an import, I receive the following output in the console:

buildActorGear.js:20 Uncaught (in promise) ReferenceError: gear is not defined
    at buildActorGear (buildActorGear.js:20)
    at buildActor (buildActor.js:19)
    at Object.callback (statblock-importer.js:43)
    at Dialog.submit (foundry.js:13466)
    at Dialog._onClickButton (foundry.js:13427)
    at HTMLButtonElement.dispatch (jquery.min.js:2)
    at HTMLButtonElement.v.handle (jquery.min.js:2)

Attempted stat block for import:
Attributes: Agility d8, Smarts d4 (A), Spirit d6,
Strength d8, Vigor d8
Skills: Athletics d8, Fighting d8, Intimidation d8, Notice d6, Stealth d8
Pace: 10; Parry: 6; Toughness: 6
Edges: Alertness

**Comment by WildBillLives** [comment]
If you add a "Gear: xxxxxx" section below your 'Edges' section it should import OK. It appears that it expects a gear section or it will not import.

**Comment by ArmandVestibule** [comment]
> 
> 
> If you add a "Gear: xxxxxx" section below your 'Edges' section it should import OK. It appears that it expects a gear section or it will not import.

This does seem to work as a workaround.

**Comment by spacemandev-git** [comment]
this is slated to be fixed in upcoming 1.2 release

**Comment by iotech-fvtt** [comment]
Still getting this error in 1.2
