### ISSUE TITLE
Multiple spaces between attributes/skills and die result in not importing the dice.

### ISSUE THREAD

**Issue by SalieriC** [Brownie79/fvtt-swade-stat-block-parser#5]
If there are multiple spaces between attribute and/or skill and its die, the die type gets not importet.
![image](https://user-images.githubusercontent.com/1230041/86406487-779a7300-bcb3-11ea-9e89-b2e82ed39037.png)
![image](https://user-images.githubusercontent.com/1230041/86406492-7b2dfa00-bcb3-11ea-921f-f9f271dbaa98.png)

**Comment by spacemandev-git** [comment]
should be fixed in 1.2.5
