### ISSUE TITLE
Error: The Compendium pack fvtt-swade-stat-block-parser.statblock-weapon already exists in the World and cannot be created.

### ISSUE THREAD

**Issue by VikingStudio** [Brownie79/fvtt-swade-stat-block-parser#7]
Whenever I enable the extension and restart the campaign it I get the titled error message.
If I remove all compendium packs that were added on enabling it, the error stops.

Here are the error logs for this issue. Tested in a brand new SWADE campaign with only this module enabled.

**Error Log:** 
{"level":"error","timestamp":"2020-07-09 15:44:57","message":"The Compendium pack fvtt-swade-stat-block-parser.statblock-weapon already exists in the World and cannot be created","stack":"Error: The Compendium pack fvtt-swade-stat-block-parser.statblock-weapon already exists in the World and cannot be created\n    at Function._onCreateCompendium (C:\\Foundry VTT\\Foundry VTT\\resources\\app\\dist\\database\\documents\\compendium.js:1:7771)\n    at Function._onManageCompendium (C:\\Foundry VTT\\Foundry VTT\\resources\\app\\dist\\database\\documents\\compendium.js:1:6935)\n    at Socket.handleEvent (C:\\Foundry VTT\\Foundry VTT\\resources\\app\\dist\\sockets.js:1:2027)\n    at Socket.emit (events.js:210:5)\n    at C:\\Foundry VTT\\Foundry VTT\\resources\\app\\node_modules\\socket.io\\lib\\socket.js:528:12\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)"}

**Debug Log:**
{"level":"error","timestamp":"2020-07-09 15:44:57","message":"The Compendium pack fvtt-swade-stat-block-parser.statblock-weapon already exists in the World and cannot be created","stack":"Error: The Compendium pack fvtt-swade-stat-block-parser.statblock-weapon already exists in the World and cannot be created\n    at Function._onCreateCompendium (C:\\Foundry VTT\\Foundry VTT\\resources\\app\\dist\\database\\documents\\compendium.js:1:7771)\n    at Function._onManageCompendium (C:\\Foundry VTT\\Foundry VTT\\resources\\app\\dist\\database\\documents\\compendium.js:1:6935)\n    at Socket.handleEvent (C:\\Foundry VTT\\Foundry VTT\\resources\\app\\dist\\sockets.js:1:2027)\n    at Socket.emit (events.js:210:5)\n    at C:\\Foundry VTT\\Foundry VTT\\resources\\app\\node_modules\\socket.io\\lib\\socket.js:528:12\n    at processTicksAndRejections (internal/process/task_queues.js:75:11)"}

**Comment by spacemandev-git** [comment]
fixed in 1.2.6
